Ensure cancellation error is raised by :func:`asncio.gather` using the error
from a cancelled child, if there is one.
