Raise :exc:`ValueError` if an opener returns a negative file-descriptor in ``_pyio``
:func:`open` to match ``_io``
