PyImport_ReInitLock() now checks for lock allocation error
